Repository ErykPiasecki07/VerbCalc, pull requests merged in 2021-11, with the labels that each got.

#32 Issue-29
  verbcalc/core/dispatcher.py
  verbcalc/core/translator/symbols.py
  verbcalc/tests/test_calculating.py
Labels: enhancement, good first issue

#36 added root handling
  verbcalc/core/dispatcher.py
  verbcalc/core/translator/symbols.py
  verbcalc/tests/test_calculating.py
Labels: enhancement, good first issue

#35 Modulo
  verbcalc/core/dispatcher.py
  verbcalc/core/translator/symbols.py
  verbcalc/tests/test_calculating.py
  verbcalc/tests/test_translator.py
Labels: enhancement, good first issue

#41 Handled division by zero
  verbcalc/core/calculate.py
  verbcalc/tests/test_calculating.py
Labels: bug

#47 [custom answers] This patch includes:
  AUTHORS.md
  verbcalc/core/answers.py
  verbcalc/core/calculate.py
  verbcalc/tests/test_answers.py
  verbcalc/tests/test_calculating.py
Labels: enhancement
