Repository ErykPiasecki07/VerbCalc, pull requests merged in 2021-10, with the labels that each got.

#18 Added new symbols
  setup.py
  verbcalc/core/symbols.py
  verbcalc/core/translator.py
  verbcalc/tests/test_translator.py
Labels: enhancement

#21 Added absolute value
  .gitignore
  verbcalc/core/symbols.py
  verbcalc/tests/test_translator.py
Labels: enhancement, good first issue

#22 Added dispatcher
  verbcalc/__init__.py
  verbcalc/core/dispatcher.py
  verbcalc/core/translator/__init__.py
  verbcalc/core/translator/symbols.py
  verbcalc/core/translator/translator.py
  verbcalc/tests/test_dispatcher.py
Labels: enhancement

#26 Hot-fix to docs
  doc/source/verbcalc.core.rst
Labels: bug, documentation

#27 Connected dispatcher to functions
  verbcalc/core/dispatcher.py
  verbcalc/tests/test_dispatcher.py
Labels: bug

#28 Added some public API
  doc/source/getting_started.rst
  doc/source/verbcalc.core.rst
  verbcalc/__init__.py
  verbcalc/core/calculate.py
  verbcalc/core/dispatcher.py
  verbcalc/tests/test_calculating.py
Labels: enhancement
